// <auto-generated />
namespace Senai.Chamados.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Altera_Coluna_Senha_Banco_10_07_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altera_Coluna_Senha_Banco_10_07_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201807102344337_Altera_Coluna_Senha_Banco_10_07_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
